# Generated by Django 5.1 on 2024-09-11 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('region', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('city', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Pickup Truck', 'Pickup Truck'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Roadster', 'Roadster'), ('Jeep', 'Jeep'), ('Limousine', 'Limousine')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
    ]
